import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const commandsDir = path.join(__dirname, "..", "commands");
const indexPath = path.join(commandsDir, "index.ts");

const commandFiles = fs
	.readdirSync(commandsDir)
	.filter(file => file.endsWith(".ts") && file !== "index.ts")
	.sort();

const commands = commandFiles.map(file => ({
	file: path.basename(file, ".ts"),
	name: path.basename(file, ".ts").replace(/-([a-z])/g, (_, c) => c.toUpperCase()),
}));

const imports = commands.map(c => `import ${c.name} from "./${c.file}";`);
const exportNames = commands.map(c => c.name);

const content = `// Auto-generated by scripts/generate-command-index.ts - do not edit manually
${imports.join("\n")}

export default [${exportNames.join(", ")}];
`;

fs.writeFileSync(indexPath, content);
console.log(`Generated ${indexPath} with ${commands.length} commands`);
